# Generated by Django 4.1.1 on 2022-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_spalni',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
