# Generated by Django 4.1.1 on 2022-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_alter_category_slug_alter_product_is_spalni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_spalni',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
