# Generated by Django 4.1.1 on 2022-09-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ctg',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
