# Generated by Django 4.1.1 on 2022-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
