# Generated by Django 4.1.1 on 2022-09-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this category belongs to. A category will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='category', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='category',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this category.', related_name='user_set', related_query_name='category', to='auth.permission', verbose_name='category permissions'),
        ),
    ]
